from typing import Protocol
from uuid import UUID

from ai_enterprise.domain.enterprise_kernel.entities import (
    EnterpriseResource,
    EnterpriseResourceAuditRecord,
    EnterpriseSchedule,
)


class EnterpriseResourceRepository(Protocol):
    async def add(self, resource: EnterpriseResource) -> None: ...
    async def get(self, resource_id: UUID) -> EnterpriseResource | None: ...
    async def get_by_key(
        self, organization_id: UUID, resource_key: str
    ) -> EnterpriseResource | None: ...
    async def list_for_organization(
        self, organization_id: UUID
    ) -> tuple[EnterpriseResource, ...]: ...
    async def add_schedule(self, schedule: EnterpriseSchedule) -> None: ...
    async def get_schedule(self, schedule_id: UUID) -> EnterpriseSchedule | None: ...
    async def get_schedule_by_key(
        self, organization_id: UUID, schedule_key: str
    ) -> EnterpriseSchedule | None: ...
    async def list_schedules_for_organization(
        self, organization_id: UUID
    ) -> tuple[EnterpriseSchedule, ...]: ...
    async def commit(self) -> None: ...


class EnterpriseKernelAuditSink(Protocol):
    async def append(self, record: EnterpriseResourceAuditRecord) -> None: ...
