"""add independent candidate patch review

Revision ID: c80980967426
Revises: d80a022f20d5
Create Date: 2026-07-31 10:42:14.491369

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c80980967426"
down_revision: str | Sequence[str] | None = "d80a022f20d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patch_review_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("work_package_id", sa.UUID(), nullable=False),
        sa.Column("execution_run_id", sa.UUID(), nullable=False),
        sa.Column("patch_artifact_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("base_commit", sa.String(length=64), nullable=False),
        sa.Column("expected_patch_sha256", sa.String(length=64), nullable=False),
        sa.Column("actual_patch_sha256", sa.String(length=64), nullable=True),
        sa.Column("snapshot_path", sa.Text(), nullable=True),
        sa.Column("container_id", sa.String(length=128), nullable=True),
        sa.Column("review_image", sa.Text(), nullable=False),
        sa.Column("review_image_digest", sa.Text(), nullable=True),
        sa.Column("decision_summary", sa.Text(), nullable=True),
        sa.Column("review_report_artifact_id", sa.UUID(), nullable=True),
        sa.Column("log_artifact_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("resulting_tree_hash", sa.String(length=64), nullable=True),
        sa.Column("review_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["execution_run_id"], ["execution_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["log_artifact_id"], ["artifacts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["patch_artifact_id"], ["artifacts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["review_report_artifact_id"], ["artifacts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["work_package_id"], ["work_packages.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "idempotency_key", name="uq_patch_review_project_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_patch_review_runs_execution_run_id"),
        "patch_review_runs",
        ["execution_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patch_review_runs_project_id"), "patch_review_runs", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_patch_review_runs_status"), "patch_review_runs", ["status"], unique=False
    )
    op.create_table(
        "patch_review_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patch_review_run_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("check_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("command", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("stdout_artifact_id", sa.UUID(), nullable=True),
        sa.Column("stderr_artifact_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patch_review_run_id"], ["patch_review_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["stderr_artifact_id"], ["artifacts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["stdout_artifact_id"], ["artifacts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "patch_review_run_id", "sequence", name="uq_patch_review_check_sequence"
        ),
    )
    op.create_index(
        op.f("ix_patch_review_checks_patch_review_run_id"),
        "patch_review_checks",
        ["patch_review_run_id"],
        unique=False,
    )
    op.create_table(
        "patch_review_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patch_review_run_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patch_review_run_id"], ["patch_review_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patch_review_events_patch_review_run_id"),
        "patch_review_events",
        ["patch_review_run_id"],
        unique=False,
    )
    op.create_table(
        "patch_review_findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patch_review_run_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("line_start", sa.Integer(), nullable=True),
        sa.Column("line_end", sa.Integer(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patch_review_run_id"], ["patch_review_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patch_review_findings_patch_review_run_id"),
        "patch_review_findings",
        ["patch_review_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_patch_review_findings_patch_review_run_id"), table_name="patch_review_findings"
    )
    op.drop_table("patch_review_findings")
    op.drop_index(
        op.f("ix_patch_review_events_patch_review_run_id"), table_name="patch_review_events"
    )
    op.drop_table("patch_review_events")
    op.drop_index(
        op.f("ix_patch_review_checks_patch_review_run_id"), table_name="patch_review_checks"
    )
    op.drop_table("patch_review_checks")
    op.drop_index(op.f("ix_patch_review_runs_status"), table_name="patch_review_runs")
    op.drop_index(op.f("ix_patch_review_runs_project_id"), table_name="patch_review_runs")
    op.drop_index(op.f("ix_patch_review_runs_execution_run_id"), table_name="patch_review_runs")
    op.drop_table("patch_review_runs")
    # ### end Alembic commands ###
