"""add disposable execution runtime

Revision ID: d80a022f20d5
Revises: dada975bd485
Create Date: 2026-07-31 10:20:11.604611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd80a022f20d5'
down_revision: Union[str, Sequence[str], None] = 'dada975bd485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_package_id', sa.UUID(), nullable=False),
    sa.Column('approval_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('base_commit', sa.String(length=64), nullable=False),
    sa.Column('snapshot_path', sa.Text(), nullable=True),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('container_image', sa.Text(), nullable=False),
    sa.Column('container_image_digest', sa.Text(), nullable=True),
    sa.Column('implementation_exit_code', sa.Integer(), nullable=True),
    sa.Column('failure_code', sa.String(length=128), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('cpu_limit', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('memory_limit_bytes', sa.BigInteger(), nullable=False),
    sa.Column('pids_limit', sa.Integer(), nullable=False),
    sa.Column('network_disabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('runtime_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_file_count', sa.Integer(), nullable=True),
    sa.Column('insertions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('patch_artifact_id', sa.UUID(), nullable=True),
    sa.Column('log_artifact_id', sa.UUID(), nullable=True),
    sa.Column('patch_sha256', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['log_artifact_id'], ['artifacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patch_artifact_id'], ['artifacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_execution_run_project_idempotency')
    )
    op.create_index(op.f('ix_execution_runs_project_id'), 'execution_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_execution_runs_status'), 'execution_runs', ['status'], unique=False)
    op.create_index(op.f('ix_execution_runs_work_package_id'), 'execution_runs', ['work_package_id'], unique=False)
    op.create_table('execution_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_run_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_run_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_events_execution_run_id'), 'execution_events', ['execution_run_id'], unique=False)
    op.create_table('execution_test_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('command', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('stdout_artifact_id', sa.UUID(), nullable=True),
    sa.Column('stderr_artifact_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_run_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stderr_artifact_id'], ['artifacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stdout_artifact_id'], ['artifacts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_run_id', 'sequence', name='uq_execution_test_result_sequence')
    )
    op.create_index(op.f('ix_execution_test_results_execution_run_id'), 'execution_test_results', ['execution_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_test_results_execution_run_id'), table_name='execution_test_results')
    op.drop_table('execution_test_results')
    op.drop_index(op.f('ix_execution_events_execution_run_id'), table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_index(op.f('ix_execution_runs_work_package_id'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_status'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_project_id'), table_name='execution_runs')
    op.drop_table('execution_runs')
    # ### end Alembic commands ###
