apiVersion: v1
kind: Service
metadata:
  name: ai-enterprise-api
  namespace: ai-enterprise
spec:
  selector:
    app: ai-enterprise-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
