from typing import Protocol
from uuid import UUID

from ai_enterprise.domain.change_management.entities import (
    ChangeAuditRecord,
    ChangeDecision,
    ChangeProposal,
    ChangeSet,
    ImpactAssessment,
    ValidationPlan,
)


class GovernedChangeRepository(Protocol):
    async def add_proposal(self, proposal: ChangeProposal) -> None: ...
    async def get_proposal(self, proposal_id: UUID) -> ChangeProposal | None: ...
    async def replace_proposal(self, proposal: ChangeProposal) -> None: ...
    async def add_change_set(self, change_set: ChangeSet) -> None: ...
    async def list_change_sets(self, proposal_id: UUID) -> tuple[ChangeSet, ...]: ...
    async def get_change_set(self, change_set_id: UUID) -> ChangeSet | None: ...
    async def add_impact_assessment(self, assessment: ImpactAssessment) -> None: ...
    async def list_impact_assessments(self, proposal_id: UUID) -> tuple[ImpactAssessment, ...]: ...
    async def get_impact_assessment(self, assessment_id: UUID) -> ImpactAssessment | None: ...
    async def add_validation_plan(self, plan: ValidationPlan) -> None: ...
    async def list_validation_plans(self, proposal_id: UUID) -> tuple[ValidationPlan, ...]: ...
    async def get_validation_plan(self, plan_id: UUID) -> ValidationPlan | None: ...
    async def append_decision(self, decision: ChangeDecision) -> None: ...
    async def list_decisions(self, proposal_id: UUID) -> tuple[ChangeDecision, ...]: ...
    async def commit(self) -> None: ...


class ChangeAuditSink(Protocol):
    async def append(self, record: ChangeAuditRecord) -> None: ...
